Add php extensions required by Filament

diff --git a/.docker/laravel-installer/artisan/Dockerfile b/.docker/laravel-installer/artisan/Dockerfile
--- a/.docker/laravel-installer/artisan/Dockerfile
+++ b/.docker/laravel-installer/artisan/Dockerfile
@@ -1,9 +1,10 @@
 FROM php:8.1-fpm-alpine3.15
 
-RUN apk add --update libpq-dev \
-    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
-    && docker-php-ext-install pdo pdo_pgsql pgsql mysqli pdo_mysql \
-    && docker-php-ext-enable pdo_mysql
+RUN apk add --update libpq-dev libsodium-dev icu-dev && \
+    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
+    docker-php-ext-configure intl && \
+    docker-php-ext-install pdo pdo_pgsql pgsql mysqli pdo_mysql sodium intl && \
+    docker-php-ext-enable pdo_mysql sodium intl
 
 # Install PHP Extensions (igbinary & memcached)
 RUN apk add --no-cache --update libmemcached-libs zlib
@@ -11,26 +12,26 @@ RUN set -xe && \
     cd /tmp/ && \
     apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS && \
     apk add --no-cache --update --virtual .memcached-deps zlib-dev libmemcached-dev cyrus-sasl-dev && \
-# Install igbinary (memcached's deps)
+    # Install igbinary (memcached's deps)
     pecl install igbinary && \
-# Install memcached
+    # Install memcached
     ( \
-        pecl install --nobuild memcached && \
-        cd "$(pecl config-get temp_dir)/memcached" && \
-        phpize && \
-        ./configure --enable-memcached-igbinary && \
-        make -j$(nproc) && \
-        make install && \
-        cd /tmp/ \
+    pecl install --nobuild memcached && \
+    cd "$(pecl config-get temp_dir)/memcached" && \
+    phpize && \
+    ./configure --enable-memcached-igbinary && \
+    make -j$(nproc) && \
+    make install && \
+    cd /tmp/ \
     ) && \
-# Enable PHP extensions
+    # Enable PHP extensions
     docker-php-ext-enable igbinary memcached && \
     rm -rf /tmp/* && \
     apk del .memcached-deps .phpize-deps
 
 
-RUN docker-php-ext-configure pcntl --enable-pcntl \
-  && docker-php-ext-install \
+RUN docker-php-ext-configure pcntl --enable-pcntl && \
+    docker-php-ext-install \
     pcntl
 
 
@@ -41,14 +42,14 @@ RUN chmod +x /entrypoint/entrypoint.sh
 # Downloads Composer
 WORKDIR /app
 RUN EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')" \
-  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
-  ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
-  if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ] \
-  then \
-  >&2 echo 'ERROR: Invalid installer checksum' \
-  rm composer-setup.php \
-  exit 1 \
-  fi
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
+    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ] \
+    then \
+    >&2 echo 'ERROR: Invalid installer checksum' \
+    rm composer-setup.php \
+    exit 1 \
+    fi
 
 RUN php composer-setup.php --quiet
 RUN rm composer-setup.php
